#! /bin/sh

DATEFTM="${DATEFTM:-+%Y-%m-%d}"
SHORTFMT="${SHORTFMT:-+%d.%m.%Y}"
LABEL="${LABEL:-}"
blockdate=$(date "$DATEFTM")
shortblockdate=$(date "$SHORTFMT")

case "$BLOCK_BUTTON" in
    1|2|3) date=$(date '+%A %d %B')
export TERM=xterm
cal --color=always \
    | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
    | tail -n +2 \
    | rofi \
        -dmenu \
        -markup-rows \
        -no-fullscreen \
        -font "Hack 10" \
        -hide-scrollbar \
        -bw 2 \
        -m -3 \
        -theme-str '#window {anchor:northeast; location: northwest;}' \
        -eh 1 \
        -width -24 \
        -no-custom \
        -p "$date" > /dev/null 
    esac
echo "$LABEL$blockdate"
echo "$LABEL$shortblockdate"
