#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

echo "Init symbolic links"
mkdir -p .config/dunst
ln -sf ~/.cache/wal/dunstrc ~/.config/dunst/dunstrc
mkdir -p .config/zathura
ln -sf ~/.cache/wal/zathurarc ~/.config/zathura/zathurarc
cd "$HOME"/.config/tilix/schemes
ln -sf tilix-gruvbox/*.json .

